// GENERATED by scripts/generate-api-action-inventory.ts; do not edit manually.
export const API_ACTION_INVENTORY_SCHEMA_VERSION = 1 as const;
export const API_ACTION_INVENTORY_GENERATOR_VERSION = 1 as const;
export const API_ACTION_CATALOG_HASH = "e200dcbdbeac4e0de32ec2d19b0d0c65394db11484e5b75efec9fddaa03881a9" as const;

export const API_ACTION_DESCRIPTORS_BY_NAME = {
  "clockify_workspace_get": {
    "toolName": "clockify_workspace_get",
    "operationId": "getWorkspaceOfUser",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}",
    "description": "Get the current workspace's settings and info.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "workspace_settings",
    "actionFingerprint": "cab4622d5ef8c3154622c4525b8027fcacca504f0b1002b423cf99e7cc4cb2f4",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}\u0000workspace.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_workspace_get",
      "version": 1
    }
  },
  "clockify_approvals_list": {
    "toolName": "clockify_approvals_list",
    "operationId": "getApprovalRequests",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/approval-requests",
    "description": "List approval requests (status filter: PENDING / APPROVED / WITHDRAWN_APPROVAL).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "approvals",
    "actionFingerprint": "3666a0c746fa0e0f2149187d795d59ede9a23c8509a6aabd090c24713852f001",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/approval-requests\u0000approvals.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_approvals_list",
      "version": 1
    }
  },
  "clockify_approvals_submit": {
    "toolName": "clockify_approvals_submit",
    "operationId": "createApprrovalRequest",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/approval-requests",
    "description": "Submit ONE timesheet period for approval. Pass `week` ('this_week' or 'last_week') and the harness computes the period start, OR an explicit `periodStart` — YYYY-MM-DD or a relative day (next monday, June 1), resolved server-side; do NOT guess a calendar date. Elevated write: previews and requires confirmation. Submit one period per call.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "approvals",
    "actionFingerprint": "8632e6c80bef0bab35c4eabfcccc491d218b61e98351f016fce7a3c47b11ca5c",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/approval-requests\u0000approvals.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/approval-requests\u0000approvals.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_approvals_submit",
      "version": 1
    }
  },
  "clockify_approvals_resubmit": {
    "toolName": "clockify_approvals_resubmit",
    "operationId": "resubmitApprovalRequest",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/approval-requests/resubmit-entries-for-approval",
    "description": "Resubmit the caller's rejected/withdrawn entries for ONE approval period. Pass `week` ('this_week' or 'last_week') and the harness computes the period start, OR an explicit `periodStart` — YYYY-MM-DD or a relative day (next monday, June 1), resolved server-side; do NOT guess a calendar date. Bulk external side effect — previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "approvals",
    "actionFingerprint": "13685c73a5adb29a03462f26c87e6cb388748697f388978ec8816b1679c032b6",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/approval-requests/resubmit-entries-for-approval\u0000approvals.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/approval-requests\u0000approvals.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_approvals_resubmit",
      "version": 1
    }
  },
  "clockify_approvals_approve": {
    "toolName": "clockify_approvals_approve",
    "operationId": "updateApprovalStatus",
    "host": "api",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/approval-requests/{id}",
    "description": "Approve an approval request. External side effect (notifies the owner) — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "approvals",
    "actionFingerprint": "4342f6bc0e4f56f6a5e1de9df397442016a951be7ec8be341d45bb3a196d33db",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PATCH\u0000/workspaces/{workspaceId}/approval-requests/{id}\u0000approvals.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/approval-requests\u0000approvals.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_approvals_approve",
      "version": 1
    }
  },
  "clockify_approvals_reject": {
    "toolName": "clockify_approvals_reject",
    "operationId": "updateApprovalStatus",
    "host": "api",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/approval-requests/{id}",
    "description": "Reject an approval request. External side effect (notifies the owner) — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "approvals",
    "actionFingerprint": "be2e5c4bb58e1b1f868b1c3b59763afd1d02e5731227ce7c4cf0b22a693b28bd",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PATCH\u0000/workspaces/{workspaceId}/approval-requests/{id}\u0000approvals.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/approval-requests\u0000approvals.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_approvals_reject",
      "version": 1
    }
  },
  "clockify_approvals_withdraw": {
    "toolName": "clockify_approvals_withdraw",
    "operationId": "updateApprovalStatus",
    "host": "api",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/approval-requests/{id}",
    "description": "Withdraw a submitted or approved approval request. External side effect — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "approvals",
    "actionFingerprint": "ea7a1d4575d745ab7a52bf19efd64c165a0f072c55046c7d7538a7f351eee3e9",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PATCH\u0000/workspaces/{workspaceId}/approval-requests/{id}\u0000approvals.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/approval-requests\u0000approvals.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_approvals_withdraw",
      "version": 1
    }
  },
  "clockify_clients_list": {
    "toolName": "clockify_clients_list",
    "operationId": "getClients",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/clients",
    "description": "List clients (optional name / archived filter).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "9f6fc596d49576bb00bd8da6f3dc791b0c0fb4bfa4a8bf08436a56282be25752",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/clients\u0000clients.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_clients_list",
      "version": 1
    }
  },
  "clockify_clients_get": {
    "toolName": "clockify_clients_get",
    "operationId": "getClient",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/clients/{id}",
    "description": "Fetch a single client by id, or by its exact `name` (resolved server-side).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "65655e68c9d16c493e108d35c0e9fb5f8eb9d30a140ea5352503a273e08099ae",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/clients/{id}\u0000clients.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/clients\u0000clients.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_clients_get",
      "version": 1
    }
  },
  "clockify_custom_fields_list": {
    "toolName": "clockify_custom_fields_list",
    "operationId": "ofWorkspace",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/custom-fields",
    "description": "List the workspace custom fields.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "custom_fields",
    "actionFingerprint": "616092869dfa808a62d91099ca38e9ce1c9bf64a592ff0b963309d0f4f66ffbe",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/custom-fields\u0000custom-fields.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_custom_fields_list",
      "version": 1
    }
  },
  "clockify_custom_fields_delete": {
    "toolName": "clockify_custom_fields_delete",
    "operationId": "delete",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/custom-fields/{id}",
    "description": "Delete a custom field. Destructive — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "custom_fields",
    "actionFingerprint": "df6c45bda4afe812186f3649380a98933d6f86e746e70d62006094c7ea460749",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/custom-fields/{id}\u0000custom-fields.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/custom-fields\u0000custom-fields.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_custom_fields_delete",
      "version": 1
    }
  },
  "clockify_expenses_list": {
    "toolName": "clockify_expenses_list",
    "operationId": "getExpenses",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/expenses",
    "description": "List expenses. `start`/`end` accept YYYY-MM-DD, a full ISO instant, or a relative day/period (today, yesterday, last month — resolved server-side; never guess a calendar date).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "expenses",
    "actionFingerprint": "63833c60021b853e159a6f6c714c923114c58ea90f8e269120860f1986f03529",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/expenses\u0000expenses.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_expenses_list",
      "version": 1
    }
  },
  "clockify_expenses_create": {
    "toolName": "clockify_expenses_create",
    "operationId": "createExpense",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/expenses",
    "description": "Create an expense. `date` accepts YYYY-MM-DD or a relative 'today'/'yesterday' (resolved server-side; defaults to today — never guess a calendar date). Pass `categoryId`, or the exact `categoryName` and the harness resolves it. Link a project/task by id or exact name (`projectId`/`projectName`, `taskId`/`taskName`) — also resolved server-side. Defaults to YOUR expense; to log it for another user pass their `userId` or exact `userName` (or 'me' for yourself). Billing action — previews and requires confirmation.",
    "requiredArguments": [
      "amount"
    ],
    "access": "write",
    "featureGroup": "expenses",
    "actionFingerprint": "3d497183b9e9328c819548b616ebe8a2ec140fe5c8306e2d9e6a71f9189feb6f",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/expenses\u0000expenses.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/expenses\u0000expenses.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/expenses/categories\u0000expenses.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{projectId}/tasks\u0000tasks.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{projectId}/tasks/{id}\u0000tasks.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_expenses_create",
      "version": 1
    }
  },
  "clockify_expenses_categories_list": {
    "toolName": "clockify_expenses_categories_list",
    "operationId": "getCategories",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/expenses/categories",
    "description": "List expense categories.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "expenses",
    "actionFingerprint": "343367c06444fdca296f257b69869fd0d8d143c741f292e14dca97f4a475fefb",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/expenses/categories\u0000expenses.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_expenses_categories_list",
      "version": 1
    }
  },
  "clockify_expenses_categories_create": {
    "toolName": "clockify_expenses_categories_create",
    "operationId": "createExpenseCategory",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/expenses/categories",
    "description": "Create an expense category. Billing action — previews and requires confirmation.",
    "requiredArguments": [
      "name"
    ],
    "access": "write",
    "featureGroup": "expenses",
    "actionFingerprint": "96705001fac50dde416dc8cf84d6121a12848e393e1e5967bee2d48b4fc94652",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/expenses/categories\u0000expenses.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/expenses/categories\u0000expenses.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_expenses_categories_create",
      "version": 1
    }
  },
  "clockify_expenses_delete": {
    "toolName": "clockify_expenses_delete",
    "operationId": "deleteExpense",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/expenses/{id}",
    "description": "Delete an expense. Destructive billing action — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "expenses",
    "actionFingerprint": "7747132e57ef88487e804544b81338e10ae9a48f02d57dc1ff8b3e8d7dbd9b43",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/expenses/{id}\u0000expenses.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/expenses/{id}\u0000expenses.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_expenses_delete",
      "version": 1
    }
  },
  "clockify_expenses_get": {
    "toolName": "clockify_expenses_get",
    "operationId": "getExpense",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/expenses/{id}",
    "description": "Fetch a single expense by id.",
    "requiredArguments": [
      "id"
    ],
    "access": "read",
    "featureGroup": "expenses",
    "actionFingerprint": "8b1ddb1260f20c7b1399b3267c1dad8a1e01625fce7c70c621102846069ddb76",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/expenses/{id}\u0000expenses.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_expenses_get",
      "version": 1
    }
  },
  "clockify_expenses_update": {
    "toolName": "clockify_expenses_update",
    "operationId": "updateExpense",
    "host": "api",
    "method": "PUT",
    "path": "/workspaces/{workspaceId}/expenses/{id}",
    "description": "Update an expense. Category/project/task accept an id or the exact name (`categoryName`/`projectName`/`taskName`) — resolved server-side. Billing action — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "expenses",
    "actionFingerprint": "69d1d9d0585523459dc6778aa0994e7eee8cd035ad529c5cf0b570ccdb9625db",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PUT\u0000/workspaces/{workspaceId}/expenses/{id}\u0000expenses.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/expenses/categories\u0000expenses.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/expenses/{id}\u0000expenses.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{projectId}/tasks\u0000tasks.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{projectId}/tasks/{id}\u0000tasks.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_expenses_update",
      "version": 1
    }
  },
  "clockify_holidays_list": {
    "toolName": "clockify_holidays_list",
    "operationId": "getHolidays",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/holidays",
    "description": "List the workspace holidays.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "841170ef18a9a97a4df5da39325fe23cc107cb5027885412fe47b7f2ee08873f",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/holidays\u0000holidays.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_holidays_list",
      "version": 1
    }
  },
  "clockify_holidays_in_period": {
    "toolName": "clockify_holidays_in_period",
    "operationId": "getHolidaysInPeriod",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/holidays/in-period",
    "description": "List holidays assigned to a user across a date period (defaults to you; `assignedTo` accepts a user id, exact name, or 'me'). `start`/`end` accept YYYY-MM-DD or a relative day/period (today, next month…), resolved server-side.",
    "requiredArguments": [
      "end",
      "start"
    ],
    "access": "read",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "5dbc77b19e1bd736f509afc69693130a5337695dc2332571f336f63543af54ee",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/holidays/in-period\u0000holidays.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_holidays_in_period",
      "version": 1
    }
  },
  "clockify_holidays_delete": {
    "toolName": "clockify_holidays_delete",
    "operationId": "deleteHoliday",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/holidays/{id}",
    "description": "Delete a workspace holiday. Destructive — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "d986c9afaacabd7680f5da2d819c95efde5ebaa0c351e8fe4c196afb92507ac1",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/holidays/{id}\u0000holidays.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/holidays\u0000holidays.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_holidays_delete",
      "version": 1
    }
  },
  "clockify_invoices_list": {
    "toolName": "clockify_invoices_list",
    "operationId": "getInvoices",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/invoices",
    "description": "List invoices (optional live status filter).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "invoices",
    "actionFingerprint": "3569d4a733498491c2af290c63001ac33aa92282fbde9c7d78c0ad1162b2a998",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_list",
      "version": 1
    }
  },
  "clockify_invoices_delete": {
    "toolName": "clockify_invoices_delete",
    "operationId": "deleteInvoice",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/invoices/{id}",
    "description": "Delete an invoice, by id or by its `number` (resolved server-side). Destructive billing action — previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "invoices",
    "actionFingerprint": "e65e2a3862b374c40823d036325d5495af1cc96ca96ad759ffea8c57604128cd",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/invoices/{id}\u0000invoices.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}\u0000invoices.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_delete",
      "version": 1
    }
  },
  "clockify_invoices_get": {
    "toolName": "clockify_invoices_get",
    "operationId": "getInvoice",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/invoices/{id}",
    "description": "Fetch a single invoice by id or by its `number` (line items embedded) — both resolved server-side.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "invoices",
    "actionFingerprint": "09d401c6cd053b5529d3500284cac643a8e6807a5115d46d75dfafa8b16edd6b",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}\u0000invoices.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_get",
      "version": 1
    }
  },
  "clockify_invoices_items_list": {
    "toolName": "clockify_invoices_items_list",
    "operationId": "getInvoice",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/invoices/{id}",
    "description": "List the line items on an invoice (by invoice id or `number`).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "invoices",
    "actionFingerprint": "df011e9834349d1d4c624b247be271cb698cecbb6f898450a4f09978c8a228f1",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}\u0000invoices.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_items_list",
      "version": 1
    }
  },
  "clockify_invoices_export": {
    "toolName": "clockify_invoices_export",
    "operationId": "exportInvoice",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/invoices/{id}/export",
    "description": "Export an invoice as a short-lived authenticated PDF artifact, by invoice id or `number`. Read — no confirmation.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "invoices",
    "actionFingerprint": "98877e7b6c1601441dd2136d4b0c4b96fa6b615a8e3858ad97214027e5b3c27f",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}/export\u0000invoices.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_export",
      "version": 1
    }
  },
  "clockify_invoices_items_add": {
    "toolName": "clockify_invoices_items_add",
    "operationId": "addInvoiceItem",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/invoices/{id}/items",
    "description": "Add a line item to an invoice. An amount alone is enough — description (defaults to the item type), quantity (1) and itemType (discovered from the workspace) all default server-side, so don't ask the admin for them. Billing action — previews and requires confirmation. `itemType` names a workspace-configured invoice item type; pass the one the admin asked for (e.g. \"service\") — the harness checks it against the workspace's actual types and, if it isn't configured, asks the admin to pick from the real list (it never guesses).",
    "requiredArguments": [
      "invoiceId"
    ],
    "access": "write",
    "featureGroup": "invoices",
    "actionFingerprint": "dc3bb8c9ea93f8be1095e521464f175b213d6c85db9ce14a323e57ed728c7934",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/invoices/{id}/items\u0000invoices.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}\u0000invoices.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_items_add",
      "version": 1
    }
  },
  "clockify_invoices_items_delete": {
    "toolName": "clockify_invoices_items_delete",
    "operationId": "removeInvoiceItem",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/invoices/{id}/items/{index}",
    "description": "Delete an invoice line item by its index (line order). Destructive billing action — previews and requires confirmation.",
    "requiredArguments": [
      "index",
      "invoiceId"
    ],
    "access": "write",
    "featureGroup": "invoices",
    "actionFingerprint": "fff213d50da56b9e5eadbf41a1ae513a21f7ab45e0cc12990e8959d0e004d26b",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/invoices/{id}/items/{index}\u0000invoices.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}\u0000invoices.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_items_delete",
      "version": 1
    }
  },
  "clockify_invoices_payments_list": {
    "toolName": "clockify_invoices_payments_list",
    "operationId": "getPaymentsForInvoice",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/invoices/{id}/payments",
    "description": "List the payments recorded against an invoice (by invoice id or `number`).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "invoices",
    "actionFingerprint": "dca17eaab2b01c0905e81d7e94b5a44b6a8925548bbdff4c0a8e0e22e37dc6ad",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}/payments\u0000invoices.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_payments_list",
      "version": 1
    }
  },
  "clockify_invoices_payments_create": {
    "toolName": "clockify_invoices_payments_create",
    "operationId": "createInvoicePayment",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/invoices/{id}/payments",
    "description": "Record a payment against an invoice. Payment action — previews and requires confirmation.",
    "requiredArguments": [
      "amount",
      "invoiceId",
      "paymentDate"
    ],
    "access": "write",
    "featureGroup": "invoices",
    "actionFingerprint": "9f9a6a1bc9fe21145d77e7a1d4ccfbb70b1b3c503688f0a3e3b75e514edefaf9",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/invoices/{id}/payments\u0000invoices.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}\u0000invoices.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}/payments\u0000invoices.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_payments_create",
      "version": 1
    }
  },
  "clockify_invoices_payments_delete": {
    "toolName": "clockify_invoices_payments_delete",
    "operationId": "deletePaymentById",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/invoices/{id}/payments/{paymentId}",
    "description": "Delete a recorded invoice payment. Destructive payment action — previews and requires confirmation.",
    "requiredArguments": [
      "invoiceId",
      "paymentId"
    ],
    "access": "write",
    "featureGroup": "invoices",
    "actionFingerprint": "f19dea6397f81846494351cdcae5b4cedd803a59ea06ccc0bf5aefcb25aa57ef",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/invoices/{id}/payments/{paymentId}\u0000invoices.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices\u0000invoices.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}\u0000invoices.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/invoices/{id}/payments\u0000invoices.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_invoices_payments_delete",
      "version": 1
    }
  },
  "clockify_projects_list": {
    "toolName": "clockify_projects_list",
    "operationId": "getProjects",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/projects",
    "description": "List projects, optionally filtered by name, archived state, or client ids.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "1643566ea0c762eb0b527b04ca59d9743e73ac3036da23e74546f3d8ebf75fa7",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_projects_list",
      "version": 1
    }
  },
  "clockify_templates_list": {
    "toolName": "clockify_templates_list",
    "operationId": "getProjects",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/projects",
    "description": "List project templates in the workspace.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "26a7eb3814477a5264dcfa4c8a26b513b488d8d7a24ca4268eebc52400e5f306",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000workspace.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_templates_list",
      "version": 1
    }
  },
  "clockify_projects_create": {
    "toolName": "clockify_projects_create",
    "operationId": "createNewProject",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/projects",
    "description": "Create a project. Assign a client by `clientId` or its exact `clientName` (resolved server-side — an unknown client clarifies). Optionally set the project's DEFAULT billable/cost rate with `hourlyRate`/`costRate` (a number; `rateUnit` major by default — Clockify's project rate is set here, not via a separate endpoint). Safe write — executes immediately when policy allows.",
    "requiredArguments": [
      "name"
    ],
    "access": "write",
    "featureGroup": "work_structure",
    "actionFingerprint": "78dc612fa6e9db7b72b08c43918817442c4f97fb42845b472942e792d3cb5549",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/projects\u0000projects.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/clients\u0000clients.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/clients/{id}\u0000clients.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_projects_create",
      "version": 1
    }
  },
  "clockify_projects_from_template": {
    "toolName": "clockify_projects_from_template",
    "operationId": "createProjectFromTemplate",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/projects/from-template",
    "description": "Create a project from an existing project template. Pass `templateId` or the exact `templateName` (resolved server-side — an unknown template clarifies with the real list), plus the new project's `name` (required by the API).",
    "requiredArguments": [
      "name"
    ],
    "access": "write",
    "featureGroup": "work_structure",
    "actionFingerprint": "3d4807fc2b0f3d509676733fa05fe5f5290ff6d295acd13783ef395f53b89fd7",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/projects/from-template\u0000projects.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000workspace.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_projects_from_template",
      "version": 1
    }
  },
  "clockify_projects_get": {
    "toolName": "clockify_projects_get",
    "operationId": "getProject",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/projects/{id}",
    "description": "Fetch a single project by id, or by its exact `name` (resolved server-side).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "02af33ea7b4581c0ab4dbafc9980dbb4681efcfff53440e6f55fd4741351c85b",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_projects_get",
      "version": 1
    }
  },
  "clockify_templates_get": {
    "toolName": "clockify_templates_get",
    "operationId": "getProject",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/projects/{id}",
    "description": "Fetch a single project template by id, or by its exact `name` (resolved server-side).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "bed5a8907feba1fe5e25e3e31d33a53285aac747344dac565de623c8d74da57c",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000workspace.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000workspace.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_templates_get",
      "version": 1
    }
  },
  "clockify_projects_archive": {
    "toolName": "clockify_projects_archive",
    "operationId": "updateProject",
    "host": "api",
    "method": "PUT",
    "path": "/workspaces/{workspaceId}/projects/{id}",
    "description": "Archive a project (hides it from active lists). Pass the project id, or its exact `name` and the harness resolves it. Previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "work_structure",
    "actionFingerprint": "0bd501bafabd102dc3df2f21191903be53698eb0f9781d3d8410570d2fb99579",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PUT\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_projects_archive",
      "version": 1
    }
  },
  "clockify_projects_update": {
    "toolName": "clockify_projects_update",
    "operationId": "updateProject",
    "host": "api",
    "method": "PUT",
    "path": "/workspaces/{workspaceId}/projects/{id}",
    "description": "Update a project's fields (rename, reassign client, billing, color, visibility). Pass the project's `id`, or its exact `currentName` and the harness resolves it — use this to RENAME (`currentName` + the new `name`) without listing first. Elevated write — previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "work_structure",
    "actionFingerprint": "401ae5d6a3d3107b31bca0a04f181e0c3e42d77cb2c02fc81b0c5f627dec564f",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PUT\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/clients\u0000clients.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/clients/{id}\u0000clients.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_projects_update",
      "version": 1
    }
  },
  "clockify_tasks_list": {
    "toolName": "clockify_tasks_list",
    "operationId": "getTasks",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/projects/{projectId}/tasks",
    "description": "List tasks under a project (optional name filter).",
    "requiredArguments": [
      "projectId"
    ],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "0853d3dc2a4d96d7b987d1ab271c9ef3f89f0ad0e1df15dcc9b3c61567088504",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{projectId}/tasks\u0000tasks.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_tasks_list",
      "version": 1
    }
  },
  "clockify_tasks_get": {
    "toolName": "clockify_tasks_get",
    "operationId": "getTask",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/projects/{projectId}/tasks/{id}",
    "description": "Fetch a single task within a project — by id or exact `name`, in a project given by `projectId` or `projectName` (resolved server-side).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "a9e10d6c1cb6ce4b5131efed56c5d855c9882ee8541ad42a15583673e7616084",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{projectId}/tasks/{id}\u0000tasks.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{projectId}/tasks\u0000tasks.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_tasks_get",
      "version": 1
    }
  },
  "clockify_scheduling_assignments_list": {
    "toolName": "clockify_scheduling_assignments_list",
    "operationId": "getAllAssignments",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/scheduling/assignments/all",
    "description": "List scheduling assignments in a date range (optional user/project filter; `userId` accepts a user id, exact name, or 'me'). `start`/`end` accept YYYY-MM-DD, a full ISO instant, or a relative day (today/next monday…), resolved server-side.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "scheduling",
    "actionFingerprint": "bd497315fabd80f3b90083296d186cc51b60c2fbe3477614a7f5544c0ce5ff63",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/scheduling/assignments/all\u0000scheduling.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_scheduling_assignments_list",
      "version": 1
    }
  },
  "clockify_scheduling_publish": {
    "toolName": "clockify_scheduling_publish",
    "operationId": "publishAssignments",
    "host": "api",
    "method": "PUT",
    "path": "/workspaces/{workspaceId}/scheduling/assignments/publish",
    "description": "Publish draft scheduling assignments in a date range. Publishes ALL drafts overlapping the range unless you pass `userId` (or a user's exact name / 'me') to scope it to one person. External side effect (notifies assignees) — previews and requires confirmation.",
    "requiredArguments": [
      "end",
      "start"
    ],
    "access": "write",
    "featureGroup": "scheduling",
    "actionFingerprint": "4243e1950996bc029605bb44488206accaf6621d5cc69cb485c00dd1ed26e286",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PUT\u0000/workspaces/{workspaceId}/scheduling/assignments/publish\u0000scheduling.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/scheduling/assignments/all\u0000scheduling.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_scheduling_publish",
      "version": 1
    }
  },
  "clockify_scheduling_assignments_create": {
    "toolName": "clockify_scheduling_assignments_create",
    "operationId": "createRecurring",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/scheduling/assignments/recurring",
    "description": "Create a scheduling assignment (draft) for ONE user (Clockify scheduling is per-user — there is no group assignment). Pass `userId` and `projectId` as ids or exact names (or 'me' for the user) — resolved server-side, clarifies on an unknown one. `start`/`end` accept YYYY-MM-DD or a relative day (today/next monday…). Safe write — executes immediately when policy allows.",
    "requiredArguments": [
      "end",
      "hoursPerDay",
      "projectId",
      "start",
      "userId"
    ],
    "access": "write",
    "featureGroup": "scheduling",
    "actionFingerprint": "7634f75c5e43786eaf66686e32710e8e85cd7dadc8ff20d3e0ef9c06162c0c15",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/scheduling/assignments/recurring\u0000scheduling.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/scheduling/assignments/all\u0000scheduling.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_scheduling_assignments_create",
      "version": 1
    }
  },
  "clockify_scheduling_assignments_delete": {
    "toolName": "clockify_scheduling_assignments_delete",
    "operationId": "deleteRRecurringAssignment",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/scheduling/assignments/recurring/{id}",
    "description": "Delete a scheduling assignment. Destructive — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "scheduling",
    "actionFingerprint": "326fa5f823f614f1ec2b82dbb02dd27af1a2c98dd1060b9c3f4e2fb098b2b5e9",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/scheduling/assignments/recurring/{id}\u0000scheduling.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/scheduling/assignments/all\u0000scheduling.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_scheduling_assignments_delete",
      "version": 1
    }
  },
  "clockify_scheduling_assignments_update": {
    "toolName": "clockify_scheduling_assignments_update",
    "operationId": "editRecurring",
    "host": "api",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/scheduling/assignments/recurring/{id}",
    "description": "Update a scheduling assignment. Elevated write — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "scheduling",
    "actionFingerprint": "9eabdd6620fc82f18049fb469f9fe2669ceca3afbbda72ff2310e201b138826c",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PATCH\u0000/workspaces/{workspaceId}/scheduling/assignments/recurring/{id}\u0000scheduling.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/scheduling/assignments/all\u0000scheduling.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_scheduling_assignments_update",
      "version": 1
    }
  },
  "clockify_scheduling_user_totals": {
    "toolName": "clockify_scheduling_user_totals",
    "operationId": "getUserTotalsForSingleUser",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/scheduling/assignments/users/{userId}/totals",
    "description": "Get a user's scheduled-hours totals in a date range (defaults to you; `userId` accepts a user id, exact name, or 'me'; `start`/`end` accept relative days, resolved server-side).",
    "requiredArguments": [
      "end",
      "start"
    ],
    "access": "read",
    "featureGroup": "scheduling",
    "actionFingerprint": "362dac1424d02f6eae6be83cae2dfb10dfc39118bba60b59e3c2b17689850302",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/scheduling/assignments/users/{userId}/totals\u0000scheduling.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_scheduling_user_totals",
      "version": 1
    }
  },
  "clockify_tags_list": {
    "toolName": "clockify_tags_list",
    "operationId": "getTags",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/tags",
    "description": "List tags (optional name / archived filter).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "e8a1d87f8094f96ff039322124649f50956ebe0b74784530c86c89fb828f0724",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/tags\u0000tags.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_tags_list",
      "version": 1
    }
  },
  "clockify_tags_create": {
    "toolName": "clockify_tags_create",
    "operationId": "createNewTag",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/tags",
    "description": "Create a tag. Safe write — executes immediately when policy allows.",
    "requiredArguments": [
      "name"
    ],
    "access": "write",
    "featureGroup": "work_structure",
    "actionFingerprint": "1815fe81ac1e4b8154b96603547229ebbf9adb02a3d479a7cc9e7ffd4685a8b9",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/tags\u0000tags.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/tags\u0000tags.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_tags_create",
      "version": 1
    }
  },
  "clockify_tags_delete": {
    "toolName": "clockify_tags_delete",
    "operationId": "deleteTag",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/tags/{id}",
    "description": "Delete a tag. Pass the tag's id (preferred — list tags first to get it), or its exact name and the harness resolves it to an id. Previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "work_structure",
    "actionFingerprint": "630d377c713176eb7c04e32e1800614ce767dce922bbf2288dc69028af481fe3",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/tags/{id}\u0000tags.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/tags\u0000tags.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/tags/{id}\u0000tags.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_tags_delete",
      "version": 1
    }
  },
  "clockify_tags_get": {
    "toolName": "clockify_tags_get",
    "operationId": "getTag",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/tags/{id}",
    "description": "Fetch a single tag by id, or by its exact `name` (resolved server-side).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "work_structure",
    "actionFingerprint": "ac4a2eb0f82b1400f5df39438061b4aea7bb9517aa840fc3af445784136d94b7",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/tags/{id}\u0000tags.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/tags\u0000tags.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_tags_get",
      "version": 1
    }
  },
  "clockify_tags_update": {
    "toolName": "clockify_tags_update",
    "operationId": "updateTag",
    "host": "api",
    "method": "PUT",
    "path": "/workspaces/{workspaceId}/tags/{id}",
    "description": "Update a tag (rename, archived). Pass the tag's `id`, or its exact `currentName` and the harness resolves it — use this to RENAME (`currentName` + the new `name`) without listing first. Elevated write — previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "work_structure",
    "actionFingerprint": "8e2b1cd7a93e7205f7165f521917a9cecf2c53640422bf885569196932f78ec1",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PUT\u0000/workspaces/{workspaceId}/tags/{id}\u0000tags.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/tags\u0000tags.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/tags/{id}\u0000tags.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_tags_update",
      "version": 1
    }
  },
  "clockify_entries_delete": {
    "toolName": "clockify_entries_delete",
    "operationId": "deleteTimeEntry",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/time-entries/{id}",
    "description": "Delete a time entry. Previews first and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "time_tracking",
    "actionFingerprint": "051bf8360baacd1795467ada4ad81c965b28368b93d38cfd2cfeea3f682929bb",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/time-entries/{id}\u0000time-entries.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-entries/{id}\u0000time-entries.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_entries_delete",
      "version": 1
    }
  },
  "clockify_entries_get": {
    "toolName": "clockify_entries_get",
    "operationId": "getTimeEntry",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/time-entries/{id}",
    "description": "Fetch a single time entry by id.",
    "requiredArguments": [
      "id"
    ],
    "access": "read",
    "featureGroup": "time_tracking",
    "actionFingerprint": "ebe96436e56a24329cf05ac9fde5b280514df9329a9d15d303a8c55c6fc4dc3a",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-entries/{id}\u0000time-entries.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_entries_get",
      "version": 1
    }
  },
  "clockify_time_off_balance_get": {
    "toolName": "clockify_time_off_balance_get",
    "operationId": "getBalancesForUser",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/time-off/balance/user/{userId}",
    "description": "Get a user's time-off balances (defaults to you; `userId` accepts a user id, exact name, or 'me').",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "b171aaa59cef3498787175232519ff6d862e39aca85b9316a147195e8102e9eb",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/balance/user/{userId}\u0000time-off.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_time_off_balance_get",
      "version": 1
    }
  },
  "clockify_time_off_policies_list": {
    "toolName": "clockify_time_off_policies_list",
    "operationId": "findPoliciesForWorkspace",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/time-off/policies",
    "description": "List time-off policies.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "a5103bfccb4d4ad011f1923ce38c18df0da65c13b84b8178f181c3b8ff44114d",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/policies\u0000time-off.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_time_off_policies_list",
      "version": 1
    }
  },
  "clockify_time_off_policies_get": {
    "toolName": "clockify_time_off_policies_get",
    "operationId": "getPolicy",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/time-off/policies/{id}",
    "description": "Fetch a single time-off policy by id, or by its exact `name` (resolved server-side).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "71a2b5008e41f291d5662333e20e662466de4e43261ff2e58fc612b61d04feaa",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/policies/{id}\u0000time-off.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/policies\u0000time-off.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_time_off_policies_get",
      "version": 1
    }
  },
  "clockify_time_off_policies_archive": {
    "toolName": "clockify_time_off_policies_archive",
    "operationId": "updatePolicyStatus",
    "host": "api",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/time-off/policies/{id}",
    "description": "Archive (or unarchive) a time-off policy. Destructive — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "089519e446f068507607fb5deef685c59e1373df4fad350c3c0291790cc22eb8",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PATCH\u0000/workspaces/{workspaceId}/time-off/policies/{id}\u0000time-off.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/policies/{id}\u0000time-off.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_time_off_policies_archive",
      "version": 1
    }
  },
  "clockify_time_off_requests_create": {
    "toolName": "clockify_time_off_requests_create",
    "operationId": "createTimeOffRequest",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/time-off/policies/{policyId}/requests",
    "description": "Submit a time-off request under a policy — pass `policyId` or the exact `policyName` (resolved server-side; do NOT list policies first — an unknown name clarifies with the real options). `start`/`end` accept YYYY-MM-DD or a relative day (tomorrow/next monday…). For 'N days off next/this week' you do NOT need exact dates — pass `days` + `week` and the harness picks the first N workdays (shown in the preview). Never ask which days when a week was given. For an HOUR-based policy, pass the day in `start` plus `hours` (the harness builds the hour window). External side effect (notifies approvers) — previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "d0009b85a4076179cd7f944fa093e6f7144b5a22620422f3689bd94e2dfc6222",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/time-off/policies/{policyId}/requests\u0000time-off.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/balance/user/{userId}\u0000time-off.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/policies\u0000time-off.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/policies/{id}\u0000time-off.ts",
        "read\u0000api\u0000POST\u0000/workspaces/{workspaceId}/time-off/requests\u0000time-off.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_time_off_requests_create",
      "version": 1
    }
  },
  "clockify_time_off_requests_delete": {
    "toolName": "clockify_time_off_requests_delete",
    "operationId": "deleteTimeOffRequest",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}",
    "description": "Delete a time-off request. Destructive — previews and requires confirmation.",
    "requiredArguments": [
      "policyId",
      "requestId"
    ],
    "access": "write",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "b4117892bab8faee403fd1604a686a87327dcef12f0ff20140f197cc9b5e3220",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}\u0000time-off.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/policies/{id}\u0000time-off.ts",
        "read\u0000api\u0000POST\u0000/workspaces/{workspaceId}/time-off/requests\u0000time-off.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_time_off_requests_delete",
      "version": 1
    }
  },
  "clockify_time_off_approve": {
    "toolName": "clockify_time_off_approve",
    "operationId": "changeTimeOffRequestStatus",
    "host": "api",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}",
    "description": "Approve a time-off request. External side effect (notifies the requester) — previews and requires confirmation.",
    "requiredArguments": [
      "policyId",
      "requestId"
    ],
    "access": "write",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "5142c75e5dc8115d246ff8b06bc39957ab0a66abfb21ac3c33b8ec36eb54c7c9",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PATCH\u0000/workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}\u0000time-off.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/policies/{id}\u0000time-off.ts",
        "read\u0000api\u0000POST\u0000/workspaces/{workspaceId}/time-off/requests\u0000time-off.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_time_off_approve",
      "version": 1
    }
  },
  "clockify_time_off_deny": {
    "toolName": "clockify_time_off_deny",
    "operationId": "changeTimeOffRequestStatus",
    "host": "api",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}",
    "description": "Deny a time-off request. External side effect (notifies the requester) — previews and requires confirmation.",
    "requiredArguments": [
      "policyId",
      "requestId"
    ],
    "access": "write",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "bdc7f505ce1a5b9877bd0982eecb14b669290f7ddcf28e01cdcd955a8d21644a",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PATCH\u0000/workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}\u0000time-off.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-off/policies/{id}\u0000time-off.ts",
        "read\u0000api\u0000POST\u0000/workspaces/{workspaceId}/time-off/requests\u0000time-off.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_time_off_deny",
      "version": 1
    }
  },
  "clockify_time_off_requests_list": {
    "toolName": "clockify_time_off_requests_list",
    "operationId": "getTimeOffRequest",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/time-off/requests",
    "description": "List time-off requests (optional status / user filter; `userId` accepts a user id, exact name, or 'me').",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "time_off_approvals",
    "actionFingerprint": "047bc9ecc27756e0768cc6ce4d94be0b9dda73242c7e0205c55fc73ffbc0d20f",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000POST\u0000/workspaces/{workspaceId}/time-off/requests\u0000time-off.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_time_off_requests_list",
      "version": 1
    }
  },
  "clockify_groups_list": {
    "toolName": "clockify_groups_list",
    "operationId": "getUserGroups",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/user-groups",
    "description": "List user groups.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "users_groups",
    "actionFingerprint": "904c1c1436be68375cbf3de43d015e3b2895362c8f0c6ed5b9d625de821c544b",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/user-groups\u0000users.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_groups_list",
      "version": 1
    }
  },
  "clockify_groups_create": {
    "toolName": "clockify_groups_create",
    "operationId": "createUserGroup",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/user-groups",
    "description": "Create a user group. Elevated write — previews and requires confirmation.",
    "requiredArguments": [
      "name"
    ],
    "access": "write",
    "featureGroup": "users_groups",
    "actionFingerprint": "764a48b40472e735ef39170a8018368f5557eff755ed1fc7cd61118ca9f73edc",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/user-groups\u0000users.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/user-groups\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_groups_create",
      "version": 1
    }
  },
  "clockify_groups_remove_user": {
    "toolName": "clockify_groups_remove_user",
    "operationId": "deleteUser",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/user-groups/{groupId}/users/{userId}",
    "description": "Remove a user from a group. Pass the group by `groupId`/`groupName` and the user by `userId`/`userName` (or 'me') — the harness resolves names server-side and clarifies on an unknown one. Destructive — previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "users_groups",
    "actionFingerprint": "6338a86504f407d44a0e9521e3a35ace20f471b249d1691b318c14a43572ed97",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/user-groups/{groupId}/users/{userId}\u0000users.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/user-groups\u0000users.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_groups_remove_user",
      "version": 1
    }
  },
  "clockify_groups_delete": {
    "toolName": "clockify_groups_delete",
    "operationId": "deleteUserGroup",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/user-groups/{id}",
    "description": "Delete a user group. Pass the group id, or its exact `name` and the harness resolves it. Destructive — previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "users_groups",
    "actionFingerprint": "afcb880d9362c6da37c765522a75c75ac27ae42406e69e337b124880c5f175a3",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/user-groups/{id}\u0000users.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/user-groups\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_groups_delete",
      "version": 1
    }
  },
  "clockify_groups_update": {
    "toolName": "clockify_groups_update",
    "operationId": "updateUserGroup",
    "host": "api",
    "method": "PUT",
    "path": "/workspaces/{workspaceId}/user-groups/{id}",
    "description": "Rename a user group. Elevated write — previews and requires confirmation.",
    "requiredArguments": [
      "id",
      "name"
    ],
    "access": "write",
    "featureGroup": "users_groups",
    "actionFingerprint": "303dedd8c692e52fed28c1ade0a1a6698702d1179bd940b7e5c14b8001ea6ce4",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PUT\u0000/workspaces/{workspaceId}/user-groups/{id}\u0000users.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/user-groups\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_groups_update",
      "version": 1
    }
  },
  "clockify_entries_list": {
    "toolName": "clockify_entries_list",
    "operationId": "getTimeEntries",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/user/{userId}/time-entries",
    "description": "List time entries for a user (defaults to the caller; `userId` accepts a user id, exact name, or 'me'). `start`/`end` accept YYYY-MM-DD, a full ISO instant, or a relative day (today/yesterday/last monday…) resolved server-side. Optional project/task filters — pass an id or the exact name (`projectId`/`projectName`, `taskId`/`taskName`), resolved server-side.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "time_tracking",
    "actionFingerprint": "633501a4ea89f1a9c14df24e5ad3854972dc36a9e7ded1fd9bf8ba6895af884d",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/user/{userId}/time-entries\u0000time-entries.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{projectId}/tasks\u0000tasks.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_entries_list",
      "version": 1
    }
  },
  "clockify_status": {
    "toolName": "clockify_status",
    "operationId": "getTimeEntries",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/user/{userId}/time-entries",
    "description": "Show the admin's currently running timer (if any).",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "time_tracking",
    "actionFingerprint": "525447f65632a911b90478fd4c4fec2649ecff799cea50ea88b1de91301cfd7a",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/user/{userId}/time-entries\u0000time-entries.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_status",
      "version": 1
    }
  },
  "clockify_stop_timer": {
    "toolName": "clockify_stop_timer",
    "operationId": "stopRunningTimeEntry",
    "host": "api",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/user/{userId}/time-entries",
    "description": "Stop the admin's currently running timer.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "time_tracking",
    "actionFingerprint": "93a48dcee64899eb3190129d5a54c4e855be799aba5d87be468912afbe431a06",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PATCH\u0000/workspaces/{workspaceId}/user/{userId}/time-entries\u0000time-entries.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/time-entries/{id}\u0000time-entries.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/user/{userId}/time-entries\u0000time-entries.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_stop_timer",
      "version": 1
    }
  },
  "clockify_users_list": {
    "toolName": "clockify_users_list",
    "operationId": "getUsersOfWorkspace",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/users",
    "description": "List workspace users.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "users_groups",
    "actionFingerprint": "7fbec3898ef538b42f26eabee39117f072904cb5a829abbe25020ad0d04801cb",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_users_list",
      "version": 1
    }
  },
  "clockify_users_invite": {
    "toolName": "clockify_users_invite",
    "operationId": "addUsers",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/users",
    "description": "Invite a user to the workspace by email. External side effect (may email) — previews and requires confirmation. Email is NOT sent unless sendEmail is true.",
    "requiredArguments": [
      "email"
    ],
    "access": "write",
    "featureGroup": "users_groups",
    "actionFingerprint": "b8c6ebb24ed8fbb33b24343a2ba7bab1dd0d562fdd92d593e06fecdaf69c71e8",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_users_invite",
      "version": 1
    }
  },
  "clockify_users_deactivate": {
    "toolName": "clockify_users_deactivate",
    "operationId": "updateUserStatus",
    "host": "api",
    "method": "PUT",
    "path": "/workspaces/{workspaceId}/users/{userId}",
    "description": "Deactivate a workspace user (removes their access). Pass the member by `userId`/`userName` — an id or the exact name, resolved + verified server-side. Elevated write — previews and requires confirmation.",
    "requiredArguments": [],
    "access": "write",
    "featureGroup": "users_groups",
    "actionFingerprint": "021475c1316870d1072a4bda78ae95c2d802401ab52fbcc8dbe3428e9ef9d02d",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000PUT\u0000/workspaces/{workspaceId}/users/{userId}\u0000users.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_users_deactivate",
      "version": 1
    }
  },
  "clockify_users_role_update": {
    "toolName": "clockify_users_role_update",
    "operationId": "createUserRole",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/users/{userId}/roles",
    "description": "Give a workspace member a manager role; the SCOPE depends on the role (live-verified): WORKSPACE_ADMIN = the whole workspace (no scope needed); PROJECT_MANAGER = a project (pass `projectId` or exact `projectName`); TEAM_MANAGER = a user group (pass `groupId` or exact `groupName`). Pass the RECIPIENT by `userId`/`userName` (or 'me'). Elevated write — previews and requires confirmation.",
    "requiredArguments": [
      "role"
    ],
    "access": "write",
    "featureGroup": "users_groups",
    "actionFingerprint": "35175af478d13bcaea03e6c938f722f7bda1ab4a392f4b4c6e4a760b1d3407cd",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000POST\u0000/workspaces/{workspaceId}/users/{userId}/roles\u0000users.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}\u0000workspace.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/projects/{id}\u0000projects.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/user-groups\u0000users.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/users\u0000users.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_users_role_update",
      "version": 1
    }
  },
  "clockify_webhooks_list": {
    "toolName": "clockify_webhooks_list",
    "operationId": "getWebhooks",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/webhooks",
    "description": "List webhooks in the workspace.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "webhooks",
    "actionFingerprint": "1ceeee225c8f0e0c469bb698dad1c95727916cbf620c3924d82922c0b14e8620",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/webhooks\u0000webhooks.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": false,
        "reason": "unsupported_auth_class"
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_webhooks_list",
      "version": 1
    }
  },
  "clockify_webhooks_delete": {
    "toolName": "clockify_webhooks_delete",
    "operationId": "deleteWebhook",
    "host": "api",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/webhooks/{id}",
    "description": "Delete a webhook. Destructive external side effect — previews and requires confirmation.",
    "requiredArguments": [
      "id"
    ],
    "access": "write",
    "featureGroup": "webhooks",
    "actionFingerprint": "0616f2d348fa7d01de82ab512c9e2ce23b4a757f8378ab4eaff25cf000b28428",
    "adapterEndpoints": {
      "primary": [
        "write\u0000api\u0000DELETE\u0000/workspaces/{workspaceId}/webhooks/{id}\u0000webhooks.ts"
      ],
      "support": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/webhooks\u0000webhooks.ts",
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/webhooks/{id}\u0000webhooks.ts"
      ]
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": false,
        "reason": "unsupported_auth_class"
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_webhooks_delete",
      "version": 1
    }
  },
  "clockify_webhooks_get": {
    "toolName": "clockify_webhooks_get",
    "operationId": "getWebhook",
    "host": "api",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/webhooks/{id}",
    "description": "Fetch a single webhook by id (the signing secret is never returned).",
    "requiredArguments": [
      "id"
    ],
    "access": "read",
    "featureGroup": "webhooks",
    "actionFingerprint": "5c901a2fe30a6b1348baa332128cc396d79651af6df43ba4c8cccf4b31c37898",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000GET\u0000/workspaces/{workspaceId}/webhooks/{id}\u0000webhooks.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": false,
        "reason": "unsupported_auth_class"
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_webhooks_get",
      "version": 1
    }
  },
  "clockify_webhooks_logs": {
    "toolName": "clockify_webhooks_logs",
    "operationId": "getLogsForWebhook",
    "host": "api",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/webhooks/{id}/logs",
    "description": "List delivery logs for a webhook.",
    "requiredArguments": [
      "id"
    ],
    "access": "read",
    "featureGroup": "webhooks",
    "actionFingerprint": "b39e3689c2a0b7f7dcebe6309fc74c640a89559ce6eed0ade8b752099541a9f3",
    "adapterEndpoints": {
      "primary": [
        "read\u0000api\u0000POST\u0000/workspaces/{workspaceId}/webhooks/{id}/logs\u0000webhooks.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": false,
        "reason": "unsupported_auth_class"
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_webhooks_logs",
      "version": 1
    }
  },
  "clockify_reports_detailed": {
    "toolName": "clockify_reports_detailed",
    "operationId": "generateDetailedReport",
    "host": "reports",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/reports/detailed",
    "description": "Run a detailed (entry-level) report. The date range is OPTIONAL — omitted = the last 7 days; call directly, never ask for dates.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "reports",
    "actionFingerprint": "c82dc8719724455545a112337ddf195192b08673fa552cbb2be2f22f2f5a327e",
    "adapterEndpoints": {
      "primary": [
        "read\u0000reports\u0000POST\u0000/workspaces/{workspaceId}/reports/detailed\u0000reports.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_reports_detailed",
      "version": 1
    }
  },
  "clockify_reports_summary": {
    "toolName": "clockify_reports_summary",
    "operationId": "generateSummaryReport",
    "host": "reports",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/reports/summary",
    "description": "Run a summary report (grouped, defaults to PROJECT). The date range is OPTIONAL — omitted = the last 7 days; call directly, never ask for dates.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "reports",
    "actionFingerprint": "edffb5b8625fdc1fd987e9b76fe2103bf2010b797141131e8cbad20089bfc810",
    "adapterEndpoints": {
      "primary": [
        "read\u0000reports\u0000POST\u0000/workspaces/{workspaceId}/reports/summary\u0000reports.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_reports_summary",
      "version": 1
    }
  },
  "clockify_reports_weekly": {
    "toolName": "clockify_reports_weekly",
    "operationId": "generateWeeklyReport",
    "host": "reports",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/reports/weekly",
    "description": "Run a weekly report. The date range is OPTIONAL — omitted = the last 7 days; call directly, never ask for dates.",
    "requiredArguments": [],
    "access": "read",
    "featureGroup": "reports",
    "actionFingerprint": "78a6c4f4d6f059b89b17dcdc2df8beb822d104c875a6e60a4366238e4c05e971",
    "adapterEndpoints": {
      "primary": [
        "read\u0000reports\u0000POST\u0000/workspaces/{workspaceId}/reports/weekly\u0000reports.ts"
      ],
      "support": []
    },
    "availabilityByAuthClass": {
      "addon": {
        "available": true
      },
      "api_key": {
        "available": true
      }
    },
    "presentation": {
      "presenterId": "clockify_reports_weekly",
      "version": 1
    }
  }
} as const;

export const API_ACTION_NAMES_BY_OPERATION_ID = {
  "getWorkspaceOfUser": [
    "clockify_workspace_get"
  ],
  "getApprovalRequests": [
    "clockify_approvals_list"
  ],
  "createApprrovalRequest": [
    "clockify_approvals_submit"
  ],
  "resubmitApprovalRequest": [
    "clockify_approvals_resubmit"
  ],
  "updateApprovalStatus": [
    "clockify_approvals_approve",
    "clockify_approvals_reject",
    "clockify_approvals_withdraw"
  ],
  "getClients": [
    "clockify_clients_list"
  ],
  "getClient": [
    "clockify_clients_get"
  ],
  "ofWorkspace": [
    "clockify_custom_fields_list"
  ],
  "delete": [
    "clockify_custom_fields_delete"
  ],
  "getExpenses": [
    "clockify_expenses_list"
  ],
  "createExpense": [
    "clockify_expenses_create"
  ],
  "getCategories": [
    "clockify_expenses_categories_list"
  ],
  "createExpenseCategory": [
    "clockify_expenses_categories_create"
  ],
  "deleteExpense": [
    "clockify_expenses_delete"
  ],
  "getExpense": [
    "clockify_expenses_get"
  ],
  "updateExpense": [
    "clockify_expenses_update"
  ],
  "getHolidays": [
    "clockify_holidays_list"
  ],
  "getHolidaysInPeriod": [
    "clockify_holidays_in_period"
  ],
  "deleteHoliday": [
    "clockify_holidays_delete"
  ],
  "getInvoices": [
    "clockify_invoices_list"
  ],
  "deleteInvoice": [
    "clockify_invoices_delete"
  ],
  "getInvoice": [
    "clockify_invoices_get",
    "clockify_invoices_items_list"
  ],
  "exportInvoice": [
    "clockify_invoices_export"
  ],
  "addInvoiceItem": [
    "clockify_invoices_items_add"
  ],
  "removeInvoiceItem": [
    "clockify_invoices_items_delete"
  ],
  "getPaymentsForInvoice": [
    "clockify_invoices_payments_list"
  ],
  "createInvoicePayment": [
    "clockify_invoices_payments_create"
  ],
  "deletePaymentById": [
    "clockify_invoices_payments_delete"
  ],
  "getProjects": [
    "clockify_projects_list",
    "clockify_templates_list"
  ],
  "createNewProject": [
    "clockify_projects_create"
  ],
  "createProjectFromTemplate": [
    "clockify_projects_from_template"
  ],
  "getProject": [
    "clockify_projects_get",
    "clockify_templates_get"
  ],
  "updateProject": [
    "clockify_projects_archive",
    "clockify_projects_update"
  ],
  "getTasks": [
    "clockify_tasks_list"
  ],
  "getTask": [
    "clockify_tasks_get"
  ],
  "getAllAssignments": [
    "clockify_scheduling_assignments_list"
  ],
  "publishAssignments": [
    "clockify_scheduling_publish"
  ],
  "createRecurring": [
    "clockify_scheduling_assignments_create"
  ],
  "deleteRRecurringAssignment": [
    "clockify_scheduling_assignments_delete"
  ],
  "editRecurring": [
    "clockify_scheduling_assignments_update"
  ],
  "getUserTotalsForSingleUser": [
    "clockify_scheduling_user_totals"
  ],
  "getTags": [
    "clockify_tags_list"
  ],
  "createNewTag": [
    "clockify_tags_create"
  ],
  "deleteTag": [
    "clockify_tags_delete"
  ],
  "getTag": [
    "clockify_tags_get"
  ],
  "updateTag": [
    "clockify_tags_update"
  ],
  "deleteTimeEntry": [
    "clockify_entries_delete"
  ],
  "getTimeEntry": [
    "clockify_entries_get"
  ],
  "getBalancesForUser": [
    "clockify_time_off_balance_get"
  ],
  "findPoliciesForWorkspace": [
    "clockify_time_off_policies_list"
  ],
  "getPolicy": [
    "clockify_time_off_policies_get"
  ],
  "updatePolicyStatus": [
    "clockify_time_off_policies_archive"
  ],
  "createTimeOffRequest": [
    "clockify_time_off_requests_create"
  ],
  "deleteTimeOffRequest": [
    "clockify_time_off_requests_delete"
  ],
  "changeTimeOffRequestStatus": [
    "clockify_time_off_approve",
    "clockify_time_off_deny"
  ],
  "getTimeOffRequest": [
    "clockify_time_off_requests_list"
  ],
  "getUserGroups": [
    "clockify_groups_list"
  ],
  "createUserGroup": [
    "clockify_groups_create"
  ],
  "deleteUser": [
    "clockify_groups_remove_user"
  ],
  "deleteUserGroup": [
    "clockify_groups_delete"
  ],
  "updateUserGroup": [
    "clockify_groups_update"
  ],
  "getTimeEntries": [
    "clockify_entries_list",
    "clockify_status"
  ],
  "stopRunningTimeEntry": [
    "clockify_stop_timer"
  ],
  "getUsersOfWorkspace": [
    "clockify_users_list"
  ],
  "addUsers": [
    "clockify_users_invite"
  ],
  "updateUserStatus": [
    "clockify_users_deactivate"
  ],
  "createUserRole": [
    "clockify_users_role_update"
  ],
  "getWebhooks": [
    "clockify_webhooks_list"
  ],
  "deleteWebhook": [
    "clockify_webhooks_delete"
  ],
  "getWebhook": [
    "clockify_webhooks_get"
  ],
  "getLogsForWebhook": [
    "clockify_webhooks_logs"
  ],
  "generateDetailedReport": [
    "clockify_reports_detailed"
  ],
  "generateSummaryReport": [
    "clockify_reports_summary"
  ],
  "generateWeeklyReport": [
    "clockify_reports_weekly"
  ]
} as const;
