import { readFileSync, writeFileSync } from "node:fs";
import { basename, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ENDPOINT_SCOPE_SOURCES } from "../src/addon/scope-contract.js";
import { ACTION_CATALOG } from "../src/harness/catalog.js";
import {
  adapterRequestShapeKey,
  extractAdapterEndpoints,
  type AdapterEndpoint,
} from "./lib/adapter-endpoints.js";

const repositoryRoot = fileURLToPath(new URL("../", import.meta.url));
const outputPath = resolve(repositoryRoot, "docs/ENDPOINT_SCOPE_CONTRACT.md");

function render(): string {
  const adapterEndpoints = extractAdapterEndpoints(repositoryRoot);
  const adapterRequestShapeCount = new Set(adapterEndpoints.map(adapterRequestShapeKey)).size;
  const catalogGroups = new Map<string, string[]>();
  for (const action of ACTION_CATALOG) {
    const names = catalogGroups.get(action.featureGroup) ?? [];
    names.push(action.name);
    catalogGroups.set(action.featureGroup, names);
  }

  const assignments = new Map<AdapterEndpoint, string[]>();
  const rows = ENDPOINT_SCOPE_SOURCES.map((source) => {
    const patterns = source.pathPatterns.map((pattern) => new RegExp(pattern));
    const endpoints = adapterEndpoints.filter((endpoint) =>
      endpoint.access === source.access
      && source.adapterModules.includes(endpoint.sourceModule)
      && patterns.some((pattern) => pattern.test(endpoint.rawPath)),
    );
    if (endpoints.length === 0) {
      throw new Error(`${source.scope}: retained scope has no matching adapter endpoint`);
    }
    for (const endpoint of endpoints) {
      const scopes = assignments.get(endpoint) ?? [];
      scopes.push(source.scope);
      assignments.set(endpoint, scopes);
    }

    const catalogActions = source.catalogFeatureGroups.flatMap((group) => {
      const names = catalogGroups.get(group);
      if (!names?.length) throw new Error(`${source.scope}: catalog feature group ${group} is empty or unknown`);
      return names;
    });
    const exactEndpoints = [...new Set(endpoints.map((endpoint) =>
      `${endpoint.host.toUpperCase()} ${endpoint.method} ${endpoint.rawPath}`,
    ))].sort();
    return `| \`${source.scope}\` | ${exactEndpoints.map((endpoint) => `\`${endpoint}\``).join("<br>")} | ${source.catalogFeatureGroups.map((group) => `\`${group}\``).join(", ")} (${new Set(catalogActions).size} actions) | ${source.probes.map((probe) => `\`${probe}\``).join("<br>")} |`;
  });

  const unassigned = adapterEndpoints.filter((endpoint) => !assignments.has(endpoint));
  if (unassigned.length > 0) {
    throw new Error(
      `Adapter endpoints without a retained scope:\n${unassigned.map((endpoint) =>
        `- ${endpoint.sourceModule}: ${endpoint.access} ${endpoint.host.toUpperCase()} ${endpoint.method} ${endpoint.rawPath}`,
      ).join("\n")}`,
    );
  }
  const multiplyAssigned = [...assignments.entries()].filter(([, scopes]) => scopes.length !== 1);
  if (multiplyAssigned.length > 0) {
    throw new Error(
      `Adapter callsites assigned to multiple retained scopes:\n${multiplyAssigned.map(([endpoint, scopes]) =>
        `- ${endpoint.sourceModule}: ${endpoint.access} ${endpoint.host.toUpperCase()} ${endpoint.method} ${endpoint.rawPath} -> ${scopes.join(", ")}`,
      ).join("\n")}`,
    );
  }
  const retainedScopes = ENDPOINT_SCOPE_SOURCES.map(({ scope }) => scope);
  if (new Set(retainedScopes).size !== retainedScopes.length) {
    throw new Error("Retained scope declarations must be unique");
  }

  return [
    "<!-- GENERATED by scripts/generate-endpoint-scope-contract.ts; do not edit manually. -->",
    "# Endpoint-to-scope contract",
    "",
    "This contract is extracted from the actual `src/clockify/rest/*.ts` `RestCore` calls and cross-checked against the assembled `ACTION_CATALOG`. Generation first rejects any `RestCore` callsite outside that scanned adapter root and rejects unsafe HTTP methods routed through read-only `core.call`; read-only POST searches must use `core.postQuery`. Each assignment is adapter callsite-specific (`access + host + method + normalized path + source module`) and generation fails if a callsite is unassigned or assigned to more than one retained scope, a retained scope has no exact endpoint, a catalog group is missing, or this artifact drifts. The same wire path may appear in different source modules when Clockify applies permission semantics to the operation/payload. Catalog groups are a conservative potential-consumer cross-check; they are not claimed as exact per-action call edges.",
    "",
    "`REPORTS_READ` covers POST search requests on the reports host. The add-on declares no `REPORTS_WRITE`: no report mutation exists in the adapter or catalog. `WORKSPACE_READ`/`WORKSPACE_WRITE` cover the Clockify endpoint families (workspace settings, holidays, webhooks, entity changes, and audit search) for which the SDK exposes no narrower manifest scope.",
    "",
    "Clockify's add-on authorization contract defines scopes as resource + READ/WRITE permissions and states that an endpoint called without its appropriate declared scope fails with HTTP 403. The release gate combines that platform rule with this exact one-to-one adapter assignment and `scripts/live-scope-probe.ts` against a newly issued production add-on token: every retained scope must have one distinct exact endpoint probe which clears authorization. Static extraction alone is not treated as live permission evidence.",
    "",
    `Generated inventory: **${adapterRequestShapeCount} distinct adapter request shapes**, **${ACTION_CATALOG.length} catalog actions**, **${ENDPOINT_SCOPE_SOURCES.length} retained scopes**.`,
    "",
    "| Scope | Exact adapter request shape(s) | Potential catalog feature groups | Offline request-shape probe(s) |",
    "|---|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}

const expected = render();
if (process.argv.includes("--check")) {
  if (readFileSync(outputPath, "utf8") !== expected) {
    throw new Error(`Endpoint scope contract is stale; run npm run generate:scope-contract (${basename(outputPath)}).`);
  }
} else {
  writeFileSync(outputPath, expected, "utf8");
}
